# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
"""
This file contains the exact signatures for all functions in module
PySide6.QtNetworkAuth, except for defaults which are replaced by "...".
"""

# mypy: disable-error-code="override, overload-overlap"
# Module `PySide6.QtNetworkAuth`

import PySide6.QtNetworkAuth
import PySide6.QtCore
import PySide6.QtNetwork

import enum
import typing
import collections.abc
from PySide6.QtCore import Signal
import shiboken6


class QAbstractOAuth(PySide6.QtCore.QObject):
    # authorizationUrlChanged(QUrl)
    authorizationUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]
    # authorizeWithBrowser(QUrl)
    authorizeWithBrowser: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]
    # clientIdentifierChanged(QString)
    clientIdentifierChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # contentTypeChanged(ContentType)
    contentTypeChanged: typing.ClassVar[Signal[
        [ContentType], [], [], [], [], [], [], [],
        [ContentType], [ContentType], [ContentType], [ContentType], [ContentType], [ContentType], [ContentType], [ContentType]
    ]]
    # extraTokensChanged(QVariantMap)
    extraTokensChanged: typing.ClassVar[Signal[
        [collections.abc.Mapping[str, typing.Any]], [], [], [], [], [], [], [],
        [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]]
    ]]
    # finished(QNetworkReply*)
    finished: typing.ClassVar[Signal[
        [PySide6.QtNetwork.QNetworkReply], [], [], [], [], [], [], [],
        [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply], [PySide6.QtNetwork.QNetworkReply]
    ]]
    # granted()
    granted: typing.ClassVar[Signal[
        [], [], [], [], [], [], [], [],
        [], [], [], [], [], [], [], []
    ]]
    # replyDataReceived(QByteArray)
    replyDataReceived: typing.ClassVar[Signal[
        [PySide6.QtCore.QByteArray], [], [], [], [], [], [], [],
        [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray]
    ]]
    # requestFailed(Error)
    requestFailed: typing.ClassVar[Signal[
        [Error], [], [], [], [], [], [], [],
        [Error], [Error], [Error], [Error], [Error], [Error], [Error], [Error]
    ]]
    # statusChanged(Status)
    statusChanged: typing.ClassVar[Signal[
        [Status], [], [], [], [], [], [], [],
        [Status], [Status], [Status], [Status], [Status], [Status], [Status], [Status]
    ]]
    # tokenChanged(QString)
    tokenChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]

    class ContentType(enum.Enum):
        WwwFormUrlEncoded         = 0x0
        Json                      = 0x1

    class Error(enum.Enum):
        NoError                   = 0x0
        NetworkError              = 0x1
        ServerError               = 0x2
        OAuthTokenNotFoundError   = 0x3
        OAuthTokenSecretNotFoundError = 0x4
        OAuthCallbackNotVerified  = 0x5
        ClientError               = 0x6
        ExpiredError              = 0x7

    class Stage(enum.Enum):
        RequestingTemporaryCredentials = 0x0
        RequestingAuthorization   = 0x1
        RequestingAccessToken     = 0x2
        RefreshingAccessToken     = 0x3

    class Status(enum.Enum):
        NotAuthenticated          = 0x0
        TemporaryCredentialsReceived = 0x1
        Granted                   = 0x2
        RefreshingToken           = 0x3

    def authorizationUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def callback(self, /) -> str: ...
    def clientIdentifier(self, /) -> str: ...
    def contentType(self, /) -> PySide6.QtNetworkAuth.QAbstractOAuth.ContentType: ...
    def deleteResource(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def extraTokens(self, /) -> typing.Dict[str, typing.Any]: ...
    @staticmethod
    def generateRandomString(length: int, /) -> PySide6.QtCore.QByteArray: ...
    def get(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def grant(self, /) -> None: ...
    def head(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def networkAccessManager(self, /) -> PySide6.QtNetwork.QNetworkAccessManager: ...
    def post(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def prepareRequest(self, request: PySide6.QtNetwork.QNetworkRequest, verb: PySide6.QtCore.QByteArray | bytes | bytearray | str, /, body: PySide6.QtCore.QByteArray | bytes | bytearray | str = ...) -> None: ...
    def put(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def replyHandler(self, /) -> PySide6.QtNetworkAuth.QAbstractOAuthReplyHandler: ...
    def resourceOwnerAuthorization(self, url: PySide6.QtCore.QUrl | str, parameters: typing.Dict[str, typing.Any], /) -> None: ...
    def setAuthorizationUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setClientIdentifier(self, clientIdentifier: str, /) -> None: ...
    def setContentType(self, contentType: PySide6.QtNetworkAuth.QAbstractOAuth.ContentType, /) -> None: ...
    def setModifyParametersFunction(self, modifyParametersFunction: object, /) -> None: ...
    def setNetworkAccessManager(self, networkAccessManager: PySide6.QtNetwork.QNetworkAccessManager, /) -> None: ...
    def setReplyHandler(self, handler: PySide6.QtNetworkAuth.QAbstractOAuthReplyHandler, /) -> None: ...
    def setStatus(self, status: PySide6.QtNetworkAuth.QAbstractOAuth.Status, /) -> None: ...
    def setToken(self, token: str, /) -> None: ...
    def status(self, /) -> PySide6.QtNetworkAuth.QAbstractOAuth.Status: ...
    def token(self, /) -> str: ...


class QAbstractOAuth2(PySide6.QtNetworkAuth.QAbstractOAuth):
    # accessTokenAboutToExpire()
    accessTokenAboutToExpire: typing.ClassVar[Signal[
        [], [], [], [], [], [], [], [],
        [], [], [], [], [], [], [], []
    ]]
    # authorizationCallbackReceived(QVariantMap)
    authorizationCallbackReceived: typing.ClassVar[Signal[
        [collections.abc.Mapping[str, typing.Any]], [], [], [], [], [], [], [],
        [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]]
    ]]
    # autoRefreshChanged(bool)
    autoRefreshChanged: typing.ClassVar[Signal[
        [bool], [], [], [], [], [], [], [],
        [bool], [bool], [bool], [bool], [bool], [bool], [bool], [bool]
    ]]
    # clientIdentifierSharedKeyChanged(QString)
    clientIdentifierSharedKeyChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # error(QString,QString,QUrl)
    error: typing.ClassVar[Signal[
        [str, str, PySide6.QtCore.QUrl], [str, str], [str], [], [], [], [], [],
        [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl]
    ]]
    # expirationAtChanged(QDateTime)
    expirationAtChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QDateTime], [], [], [], [], [], [], [],
        [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime]
    ]]
    # grantedScopeTokensChanged(QSet<QByteArray>)
    grantedScopeTokensChanged: typing.ClassVar[Signal[
        [collections.abc.Set[PySide6.QtCore.QByteArray]], [], [], [], [], [], [], [],
        [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]]
    ]]
    # idTokenChanged(QString)
    idTokenChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # nonceChanged(QString)
    nonceChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # nonceModeChanged(NonceMode)
    nonceModeChanged: typing.ClassVar[Signal[
        [NonceMode], [], [], [], [], [], [], [],
        [NonceMode], [NonceMode], [NonceMode], [NonceMode], [NonceMode], [NonceMode], [NonceMode], [NonceMode]
    ]]
    # refreshLeadTimeChanged(std::chrono::seconds)
    refreshLeadTimeChanged: typing.ClassVar[Signal[
        [int], [], [], [], [], [], [], [],
        [int], [int], [int], [int], [int], [int], [int], [int]
    ]]
    # refreshTokenChanged(QString)
    refreshTokenChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # requestedScopeTokensChanged(QSet<QByteArray>)
    requestedScopeTokensChanged: typing.ClassVar[Signal[
        [collections.abc.Set[PySide6.QtCore.QByteArray]], [], [], [], [], [], [], [],
        [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]], [collections.abc.Set[PySide6.QtCore.QByteArray]]
    ]]
    # responseTypeChanged(QString)
    responseTypeChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # scopeChanged(QString)
    scopeChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # serverReportedErrorOccurred(QString,QString,QUrl)
    serverReportedErrorOccurred: typing.ClassVar[Signal[
        [str, str, PySide6.QtCore.QUrl], [str, str], [str], [], [], [], [], [],
        [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl], [str, str, PySide6.QtCore.QUrl]
    ]]
    # sslConfigurationChanged(QSslConfiguration)
    sslConfigurationChanged: typing.ClassVar[Signal[
        [PySide6.QtNetwork.QSslConfiguration], [], [], [], [], [], [], [],
        [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration], [PySide6.QtNetwork.QSslConfiguration]
    ]]
    # stateChanged(QString)
    stateChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # tokenUrlChanged(QUrl)
    tokenUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]
    # userAgentChanged(QString)
    userAgentChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]

    class NonceMode(enum.Enum):
        Automatic                 = 0x0
        Enabled                   = 0x1
        Disabled                  = 0x2

    @typing.overload
    def __init__(self, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ..., *, scope: str | None = ..., grantedScopeTokens: typing.Optional[typing.Set[typing.Union[PySide6.QtCore.QByteArray, bytes, bytearray]]] = ..., requestedScopeTokens: typing.Optional[typing.Set[typing.Union[PySide6.QtCore.QByteArray, bytes, bytearray]]] = ..., userAgent: str | None = ..., clientIdentifierSharedKey: str | None = ..., state: str | None = ..., expiration: PySide6.QtCore.QDateTime | None = ..., refreshToken: str | None = ..., refreshLeadTime: int | None = ..., autoRefresh: bool | None = ..., nonceMode: PySide6.QtNetworkAuth.QAbstractOAuth2.NonceMode | None = ..., nonce: str | None = ..., idToken: str | None = ..., tokenUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, scope: str | None = ..., grantedScopeTokens: typing.Optional[typing.Set[typing.Union[PySide6.QtCore.QByteArray, bytes, bytearray]]] = ..., requestedScopeTokens: typing.Optional[typing.Set[typing.Union[PySide6.QtCore.QByteArray, bytes, bytearray]]] = ..., userAgent: str | None = ..., clientIdentifierSharedKey: str | None = ..., state: str | None = ..., expiration: PySide6.QtCore.QDateTime | None = ..., refreshToken: str | None = ..., refreshLeadTime: int | None = ..., autoRefresh: bool | None = ..., nonceMode: PySide6.QtNetworkAuth.QAbstractOAuth2.NonceMode | None = ..., nonce: str | None = ..., idToken: str | None = ..., tokenUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...

    def autoRefresh(self, /) -> bool: ...
    def clearNetworkRequestModifier(self, /) -> None: ...
    def clientIdentifierSharedKey(self, /) -> str: ...
    def createAuthenticatedUrl(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtCore.QUrl: ...
    def deleteResource(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def expirationAt(self, /) -> PySide6.QtCore.QDateTime: ...
    def get(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def grantedScopeTokens(self, /) -> typing.Set[PySide6.QtCore.QByteArray]: ...
    def head(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def idToken(self, /) -> str: ...
    def nonce(self, /) -> str: ...
    def nonceMode(self, /) -> PySide6.QtNetworkAuth.QAbstractOAuth2.NonceMode: ...
    @typing.overload
    def post(self, url: PySide6.QtCore.QUrl | str, multiPart: PySide6.QtNetwork.QHttpMultiPart, /) -> PySide6.QtNetwork.QNetworkReply: ...
    @typing.overload
    def post(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    @typing.overload
    def post(self, url: PySide6.QtCore.QUrl | str, data: PySide6.QtCore.QByteArray | bytes | bytearray | str, /) -> PySide6.QtNetwork.QNetworkReply: ...
    def prepareRequest(self, request: PySide6.QtNetwork.QNetworkRequest, verb: PySide6.QtCore.QByteArray | bytes | bytearray | str, /, body: PySide6.QtCore.QByteArray | bytes | bytearray | str = ...) -> None: ...
    @typing.overload
    def put(self, url: PySide6.QtCore.QUrl | str, multiPart: PySide6.QtNetwork.QHttpMultiPart, /) -> PySide6.QtNetwork.QNetworkReply: ...
    @typing.overload
    def put(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    @typing.overload
    def put(self, url: PySide6.QtCore.QUrl | str, data: PySide6.QtCore.QByteArray | bytes | bytearray | str, /) -> PySide6.QtNetwork.QNetworkReply: ...
    def refreshLeadTime(self, /) -> int: ...
    def refreshToken(self, /) -> str: ...
    def refreshTokens(self, /) -> None: ...
    def refreshTokensImplementation(self, /) -> None: ...
    def requestedScopeTokens(self, /) -> typing.Set[PySide6.QtCore.QByteArray]: ...
    def responseType(self, /) -> str: ...
    def scope(self, /) -> str: ...
    def setAutoRefresh(self, enable: bool, /) -> None: ...
    def setClientIdentifierSharedKey(self, clientIdentifierSharedKey: str, /) -> None: ...
    def setNonce(self, nonce: str, /) -> None: ...
    def setNonceMode(self, mode: PySide6.QtNetworkAuth.QAbstractOAuth2.NonceMode, /) -> None: ...
    def setRefreshLeadTime(self, leadTime: int, /) -> None: ...
    def setRefreshToken(self, refreshToken: str, /) -> None: ...
    def setRequestedScopeTokens(self, tokens: typing.Set[typing.Union[PySide6.QtCore.QByteArray, bytes, bytearray]], /) -> None: ...
    def setResponseType(self, responseType: str, /) -> None: ...
    def setScope(self, scope: str, /) -> None: ...
    def setSslConfiguration(self, configuration: PySide6.QtNetwork.QSslConfiguration, /) -> None: ...
    def setState(self, state: str, /) -> None: ...
    def setTokenUrl(self, tokenUrl: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setUserAgent(self, userAgent: str, /) -> None: ...
    def sslConfiguration(self, /) -> PySide6.QtNetwork.QSslConfiguration: ...
    def state(self, /) -> str: ...
    def tokenUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def userAgent(self, /) -> str: ...


class QAbstractOAuthReplyHandler(PySide6.QtCore.QObject):
    # callbackDataReceived(QByteArray)
    callbackDataReceived: typing.ClassVar[Signal[
        [PySide6.QtCore.QByteArray], [], [], [], [], [], [], [],
        [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray]
    ]]
    # callbackReceived(QVariantMap)
    callbackReceived: typing.ClassVar[Signal[
        [collections.abc.Mapping[str, typing.Any]], [], [], [], [], [], [], [],
        [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]]
    ]]
    # replyDataReceived(QByteArray)
    replyDataReceived: typing.ClassVar[Signal[
        [PySide6.QtCore.QByteArray], [], [], [], [], [], [], [],
        [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray], [PySide6.QtCore.QByteArray]
    ]]
    # tokenRequestErrorOccurred(QAbstractOAuth::Error,QString)
    tokenRequestErrorOccurred: typing.ClassVar[Signal[
        [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error], [], [], [], [], [], [],
        [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str], [PySide6.QtNetworkAuth.QAbstractOAuth.Error, str]
    ]]
    # tokensReceived(QVariantMap)
    tokensReceived: typing.ClassVar[Signal[
        [collections.abc.Mapping[str, typing.Any]], [], [], [], [], [], [], [],
        [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]], [collections.abc.Mapping[str, typing.Any]]
    ]]

    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def callback(self, /) -> str: ...
    def networkReplyFinished(self, reply: PySide6.QtNetwork.QNetworkReply, /) -> None: ...


class QIntList:
    ...


class QOAuth1(PySide6.QtNetworkAuth.QAbstractOAuth):
    # clientSharedSecretChanged(QString)
    clientSharedSecretChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # signatureMethodChanged(QOAuth1::SignatureMethod)
    signatureMethodChanged: typing.ClassVar[Signal[
        [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [], [], [], [], [], [], [],
        [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod], [PySide6.QtNetworkAuth.QOAuth1.SignatureMethod]
    ]]
    # temporaryCredentialsUrlChanged(QUrl)
    temporaryCredentialsUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]
    # tokenCredentialsUrlChanged(QUrl)
    tokenCredentialsUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]
    # tokenSecretChanged(QString)
    tokenSecretChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]

    class SignatureMethod(enum.Enum):
        Hmac_Sha1                 = 0x0
        Rsa_Sha1                  = 0x1
        PlainText                 = 0x2

    @typing.overload
    def __init__(self, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, clientIdentifier: str, clientSharedSecret: str, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def clientCredentials(self, /) -> typing.Tuple[str, str]: ...
    def clientSharedSecret(self, /) -> str: ...
    def continueGrantWithVerifier(self, verifier: str, /) -> None: ...
    def deleteResource(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    @staticmethod
    def generateAuthorizationHeader(oauthParams: typing.Dict[str, typing.Any], /) -> PySide6.QtCore.QByteArray: ...
    def get(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def grant(self, /) -> None: ...
    def head(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    @staticmethod
    def nonce() -> PySide6.QtCore.QByteArray: ...
    def post(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def prepareRequest(self, request: PySide6.QtNetwork.QNetworkRequest, verb: PySide6.QtCore.QByteArray | bytes | bytearray | str, /, body: PySide6.QtCore.QByteArray | bytes | bytearray | str = ...) -> None: ...
    def put(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def requestTemporaryCredentials(self, operation: PySide6.QtNetwork.QNetworkAccessManager.Operation, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    def requestTokenCredentials(self, operation: PySide6.QtNetwork.QNetworkAccessManager.Operation, url: PySide6.QtCore.QUrl | str, temporaryToken: typing.Tuple[str, str], /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtNetwork.QNetworkReply: ...
    @typing.overload
    def setClientCredentials(self, clientIdentifier: str, clientSharedSecret: str, /) -> None: ...
    @typing.overload
    def setClientCredentials(self, clientCredentials: typing.Tuple[str, str], /) -> None: ...
    def setClientSharedSecret(self, clientSharedSecret: str, /) -> None: ...
    def setSignatureMethod(self, value: PySide6.QtNetworkAuth.QOAuth1.SignatureMethod, /) -> None: ...
    def setTemporaryCredentialsUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    @typing.overload
    def setTokenCredentials(self, token: str, tokenSecret: str, /) -> None: ...
    @typing.overload
    def setTokenCredentials(self, tokenCredentials: typing.Tuple[str, str], /) -> None: ...
    def setTokenCredentialsUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setTokenSecret(self, tokenSecret: str, /) -> None: ...
    @typing.overload
    def setup(self, request: PySide6.QtNetwork.QNetworkRequest, signingParameters: typing.Dict[str, typing.Any], operation: PySide6.QtNetwork.QNetworkAccessManager.Operation, /) -> None: ...
    @typing.overload
    def setup(self, request: PySide6.QtNetwork.QNetworkRequest, signingParameters: typing.Dict[str, typing.Any], operationVerb: PySide6.QtCore.QByteArray | bytes | bytearray | str, /) -> None: ...
    def signatureMethod(self, /) -> PySide6.QtNetworkAuth.QOAuth1.SignatureMethod: ...
    def temporaryCredentialsUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def tokenCredentials(self, /) -> typing.Tuple[str, str]: ...
    def tokenCredentialsUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def tokenSecret(self, /) -> str: ...


class QOAuth1Signature(shiboken6.Shiboken.Object):
    class HttpRequestMethod(enum.Enum):
        Unknown                   = 0x0
        Head                      = 0x1
        Get                       = 0x2
        Put                       = 0x3
        Post                      = 0x4
        Delete                    = 0x5
        Custom                    = 0x6

    @typing.overload
    def __init__(self, other: PySide6.QtNetworkAuth.QOAuth1Signature, /) -> None: ...
    @typing.overload
    def __init__(self, /, url: PySide6.QtCore.QUrl | str = ..., method: PySide6.QtNetworkAuth.QOAuth1Signature.HttpRequestMethod = ..., parameters: typing.Dict[str, typing.Any] = ...) -> None: ...
    @typing.overload
    def __init__(self, url: PySide6.QtCore.QUrl | str, clientSharedKey: str, tokenSecret: str, /, method: PySide6.QtNetworkAuth.QOAuth1Signature.HttpRequestMethod = ..., parameters: typing.Dict[str, typing.Any] = ...) -> None: ...

    def __copy__(self, /) -> PySide6.QtNetworkAuth.QOAuth1Signature: ...
    def addRequestBody(self, body: PySide6.QtCore.QUrlQuery, /) -> None: ...
    def clientSharedKey(self, /) -> str: ...
    def customMethodString(self, /) -> PySide6.QtCore.QByteArray: ...
    def hmacSha1(self, /) -> PySide6.QtCore.QByteArray: ...
    def httpRequestMethod(self, /) -> PySide6.QtNetworkAuth.QOAuth1Signature.HttpRequestMethod: ...
    def insert(self, key: str, value: typing.Any, /) -> None: ...
    def keys(self, /) -> typing.List[str]: ...
    def parameters(self, /) -> typing.Dict[str, typing.Any]: ...
    @typing.overload  # type: ignore[misc, overload-cannot-match]
    def plainText(self, /) -> PySide6.QtCore.QByteArray: ...  # type: ignore[misc, overload-cannot-match]
    @typing.overload  # type: ignore[misc, overload-cannot-match]
    @staticmethod
    def plainText(clientSharedSecret: str, tokenSecret: str, /) -> PySide6.QtCore.QByteArray: ...  # type: ignore[misc, overload-cannot-match]
    def rsaSha1(self, /) -> PySide6.QtCore.QByteArray: ...
    def setClientSharedKey(self, secret: str, /) -> None: ...
    def setCustomMethodString(self, verb: PySide6.QtCore.QByteArray | bytes | bytearray | str, /) -> None: ...
    def setHttpRequestMethod(self, method: PySide6.QtNetworkAuth.QOAuth1Signature.HttpRequestMethod, /) -> None: ...
    def setParameters(self, parameters: typing.Dict[str, typing.Any], /) -> None: ...
    def setTokenSecret(self, secret: str, /) -> None: ...
    def setUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...
    def swap(self, other: PySide6.QtNetworkAuth.QOAuth1Signature, /) -> None: ...
    def take(self, key: str, /) -> typing.Any: ...
    def tokenSecret(self, /) -> str: ...
    def url(self, /) -> PySide6.QtCore.QUrl: ...
    def value(self, key: str, /, defaultValue: typing.Any = ...) -> typing.Any: ...


class QOAuth2AuthorizationCodeFlow(PySide6.QtNetworkAuth.QAbstractOAuth2):
    # accessTokenUrlChanged(QUrl)
    accessTokenUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]

    class PkceMethod(enum.Enum):
        S256                      = 0x0
        Plain                     = 0x1
        None_                     = 0xff

    @typing.overload
    def __init__(self, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ..., *, accessTokenUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...
    @typing.overload
    def __init__(self, clientIdentifier: str, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ..., *, accessTokenUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...
    @typing.overload
    def __init__(self, clientIdentifier: str, authorizationUrl: PySide6.QtCore.QUrl | str, accessTokenUrl: PySide6.QtCore.QUrl | str, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ..., *, accessTokenUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...
    @typing.overload
    def __init__(self, authorizationUrl: PySide6.QtCore.QUrl | str, accessTokenUrl: PySide6.QtCore.QUrl | str, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def accessTokenUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def buildAuthenticateUrl(self, /, parameters: typing.Dict[str, typing.Any] = ...) -> PySide6.QtCore.QUrl: ...
    def grant(self, /) -> None: ...
    def pkceMethod(self, /) -> PySide6.QtNetworkAuth.QOAuth2AuthorizationCodeFlow.PkceMethod: ...
    def refreshAccessToken(self, /) -> None: ...
    def refreshTokensImplementation(self, /) -> None: ...
    def requestAccessToken(self, code: str, /) -> None: ...
    def resourceOwnerAuthorization(self, url: PySide6.QtCore.QUrl | str, /, parameters: typing.Dict[str, typing.Any] = ...) -> None: ...
    def setAccessTokenUrl(self, accessTokenUrl: PySide6.QtCore.QUrl | str, /) -> None: ...
    def setPkceMethod(self, method: PySide6.QtNetworkAuth.QOAuth2AuthorizationCodeFlow.PkceMethod, /, length: int = ...) -> None: ...


class QOAuth2DeviceAuthorizationFlow(PySide6.QtNetworkAuth.QAbstractOAuth2):
    # authorizeWithUserCode(QUrl,QString,QUrl)
    authorizeWithUserCode: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str], [PySide6.QtCore.QUrl], [], [], [], [], [],
        [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl, str, PySide6.QtCore.QUrl]
    ]]
    # completeVerificationUrlChanged(QUrl)
    completeVerificationUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]
    # pollingChanged(bool)
    pollingChanged: typing.ClassVar[Signal[
        [bool], [], [], [], [], [], [], [],
        [bool], [bool], [bool], [bool], [bool], [bool], [bool], [bool]
    ]]
    # userCodeChanged(QString)
    userCodeChanged: typing.ClassVar[Signal[
        [str], [], [], [], [], [], [], [],
        [str], [str], [str], [str], [str], [str], [str], [str]
    ]]
    # userCodeExpirationAtChanged(QDateTime)
    userCodeExpirationAtChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QDateTime], [], [], [], [], [], [], [],
        [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime], [PySide6.QtCore.QDateTime]
    ]]
    # verificationUrlChanged(QUrl)
    verificationUrlChanged: typing.ClassVar[Signal[
        [PySide6.QtCore.QUrl], [], [], [], [], [], [], [],
        [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl], [PySide6.QtCore.QUrl]
    ]]

    @typing.overload
    def __init__(self, manager: PySide6.QtNetwork.QNetworkAccessManager, /, parent: PySide6.QtCore.QObject | None = ..., *, userCode: str | None = ..., verificationUrl: PySide6.QtCore.QUrl | None = ..., completeVerificationUrl: PySide6.QtCore.QUrl | None = ..., polling: bool | None = ..., userCodeExpirationAt: PySide6.QtCore.QDateTime | None = ...) -> None: ...
    @typing.overload
    def __init__(self, parent: PySide6.QtCore.QObject, /, *, userCode: str | None = ..., verificationUrl: PySide6.QtCore.QUrl | None = ..., completeVerificationUrl: PySide6.QtCore.QUrl | None = ..., polling: bool | None = ..., userCodeExpirationAt: PySide6.QtCore.QDateTime | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, userCode: str | None = ..., verificationUrl: PySide6.QtCore.QUrl | None = ..., completeVerificationUrl: PySide6.QtCore.QUrl | None = ..., polling: bool | None = ..., userCodeExpirationAt: PySide6.QtCore.QDateTime | None = ...) -> None: ...

    def completeVerificationUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def event(self, event: PySide6.QtCore.QEvent, /) -> bool: ...
    def grant(self, /) -> None: ...
    def isPolling(self, /) -> bool: ...
    def refreshTokensImplementation(self, /) -> None: ...
    def startTokenPolling(self, /) -> bool: ...
    def stopTokenPolling(self, /) -> None: ...
    def userCode(self, /) -> str: ...
    def userCodeExpirationAt(self, /) -> PySide6.QtCore.QDateTime: ...
    def verificationUrl(self, /) -> PySide6.QtCore.QUrl: ...


class QOAuthHttpServerReplyHandler(PySide6.QtNetworkAuth.QOAuthOobReplyHandler):
    @typing.overload
    def __init__(self, address: PySide6.QtNetwork.QHostAddress | PySide6.QtNetwork.QHostAddress.SpecialAddress, port: int, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...
    @typing.overload
    def __init__(self, port: int, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def callback(self, /) -> str: ...
    def callbackHost(self, /) -> str: ...
    def callbackPath(self, /) -> str: ...
    def callbackText(self, /) -> str: ...
    def close(self, /) -> None: ...
    def isListening(self, /) -> bool: ...
    @typing.overload
    def listen(self, configuration: PySide6.QtNetwork.QSslConfiguration, /, address: PySide6.QtNetwork.QHostAddress | PySide6.QtNetwork.QHostAddress.SpecialAddress = ..., port: int | None = ...) -> bool: ...
    @typing.overload
    def listen(self, /, address: PySide6.QtNetwork.QHostAddress | PySide6.QtNetwork.QHostAddress.SpecialAddress = ..., port: int | None = ...) -> bool: ...
    def port(self, /) -> int: ...
    def setCallbackHost(self, path: str, /) -> None: ...
    def setCallbackPath(self, path: str, /) -> None: ...
    def setCallbackText(self, text: str, /) -> None: ...


class QOAuthOobReplyHandler(PySide6.QtNetworkAuth.QAbstractOAuthReplyHandler):
    def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def callback(self, /) -> str: ...
    def networkReplyFinished(self, reply: PySide6.QtNetwork.QNetworkReply, /) -> None: ...


class QOAuthUriSchemeReplyHandler(PySide6.QtNetworkAuth.QOAuthOobReplyHandler):
    # redirectUrlChanged()
    redirectUrlChanged: typing.ClassVar[Signal[
        [], [], [], [], [], [], [], [],
        [], [], [], [], [], [], [], []
    ]]

    @typing.overload
    def __init__(self, parent: PySide6.QtCore.QObject, /, *, redirectUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...
    @typing.overload
    def __init__(self, /, *, redirectUrl: PySide6.QtCore.QUrl | None = ...) -> None: ...
    @typing.overload
    def __init__(self, redirectUrl: PySide6.QtCore.QUrl | str, /, parent: PySide6.QtCore.QObject | None = ...) -> None: ...

    def callback(self, /) -> str: ...
    def close(self, /) -> None: ...
    def handleAuthorizationRedirect(self, url: PySide6.QtCore.QUrl | str, /) -> bool: ...
    def isListening(self, /) -> bool: ...
    def listen(self, /) -> bool: ...
    def redirectUrl(self, /) -> PySide6.QtCore.QUrl: ...
    def setRedirectUrl(self, url: PySide6.QtCore.QUrl | str, /) -> None: ...


# eof
